sudo: false

language: java
jdk: openjdk11

before_install:
- unset _JAVA_OPTIONS

script:
- mvn -Prun-its verify

after_success:
- tail -200 target/it/multiple-engines/build.log

after_failure:
# - tail -200 target/it/modular-world-main-plain-test-module/build.log
- tail -200 target/it/multiple-engines/build.log
# - tail -200 target/it/simple/build.log
# - tail -200 target/it/timeout/build.log
